### PR TITLE
Fix: deregister fix multiple content

### LINKED ISSUE #196: Deregister removes first registration when a non-registered key is provided
## Description

I have multiple versioned content modules registered to my profile. When I deregister one of them, one of the other contents is removed from my profile.
I *think* this is caused by:
1. `get()` / `clone()` returns the wrong version for the module I'm trying to deregister - a different version than the one on my profile
2. `deregister()` doesn't check whether the key is actually included in the profile's contents. `indexOf` returns -1, so the `0th` element gets spliced off?

## To Reproduce

1. Create several content modules
2. Register them to your profile
3. Make changes to one of them outside of the SDK (by adding files to the unversioned folder for example)
4. Deregister the modules
5. Register the modules at their latest versions
6. Deregister the module you've updated

## Expected behavior

The updated module is deregistered.

## Actual behavior

A different module is deregistered.

## Screenshots

I have a recording of this happening in Hypergraph.

## System

- OS (incl. version): Windows 10
- SDK version: Hypergraph 0.4.0 / SDK 0.6.3

### PR DESCRIPTION
**Pull request by dpaez**
Closes #196

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -755,7 +759,9 @@ class SDK extends EventEmitter {
     const dkey = DatEncoding.encode(
       crypto.discoveryKey(DatEncoding.decode(keyString))
     )
-    archive = this.drives.get(version ? `${dkey}+${version}` : dkey)
+    // archive = this.drives.get(version ? `${dkey}+${version}` : dkey)
+    archive = this.drives.get(dkey)
+    if (indexJSON.p2pcommons.type === 'profile') debugger
```
Comment (juliangruber) [inline index.js:764]: debugger

**Comment by dpaez** [comment]
rebased and ready to merge
